import os
import sys
import json

def get_palette_for_name(name):
    # Elegant color palettes for autogenerated themes based on folder name hash
    palettes = [
        {"bg": "linear-gradient(135deg, #09090b 0%, #18181b 100%)", "header": "#a1a1aa", "card": "rgba(161, 161, 170, 0.08)", "text_h": "#09090b", "content_bg": "#09090b", "content_text": "#a1a1aa", "desc": "📂 Módulo de projeto genérico detectado automaticamente"},
        {"bg": "linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%)", "header": "#818cf8", "card": "rgba(129, 140, 248, 0.08)", "text_h": "#0f172a", "content_bg": "#090d16", "content_text": "#818cf8", "desc": "⚡ Integrações dinâmicas e APIs estruturadas"},
        {"bg": "linear-gradient(135deg, #022c22 0%, #064e3b 100%)", "header": "#34d399", "card": "rgba(52, 211, 153, 0.08)", "text_h": "#022c22", "content_bg": "#021e17", "content_text": "#34d399", "desc": "🌿 Ativos e rotinas carregados de forma dinâmica"},
        {"bg": "linear-gradient(135deg, #1c1917 0%, #44403c 100%)", "header": "#fb923c", "card": "rgba(251, 146, 60, 0.08)", "text_h": "#1c1917", "content_bg": "#12100e", "content_text": "#fb923c", "desc": "⚙️ Fluxo e scripts de automação robustos"},
        {"bg": "linear-gradient(135deg, #172554 0%, #1e3a8a 100%)", "header": "#60a5fa", "card": "rgba(96, 165, 250, 0.08)", "text_h": "#172554", "content_bg": "#0f172a", "content_text": "#60a5fa", "desc": "⚡ Serviços integrados no portfólio"},
        {"bg": "linear-gradient(135deg, #311042 0%, #4c1d95 100%)", "header": "#c084fc", "card": "rgba(192, 132, 252, 0.08)", "text_h": "#311042", "content_bg": "#1e112a", "content_text": "#c084fc", "desc": "🔮 Scripts e rotinas do banco de projetos"},
        {"bg": "linear-gradient(135deg, #450a0a 0%, #7f1d1d 100%)", "header": "#f87171", "card": "rgba(248, 113, 113, 0.08)", "text_h": "#450a0a", "content_bg": "#2d0808", "content_text": "#f87171", "desc": "🔥 Processamento de alto rendimento e utilitários"},
        {"bg": "linear-gradient(135deg, #062f4f 0%, #000000 100%)", "header": "#00ffcc", "card": "rgba(0, 255, 204, 0.08)", "text_h": "#000000", "content_bg": "#010811", "content_text": "#00ffcc", "desc": "💎 Recursos de última geração carregados da pasta"}
    ]
    hash_val = 0
    for char in name:
        hash_val = ord(char) + ((hash_val << 5) - hash_val)
    index = abs(hash_val) % len(palettes)
    return palettes[index]

def list_themes():
    root_path = os.getcwd()
    excluded_folders = {
        "node_modules", "src", "assets", "dist", "public", ".git", ".github", ".vscode", "tmp", "coverage", ".cursor"
    }

    folders = []
    for item in os.listdir(root_path):
        if os.path.isdir(os.path.join(root_path, item)) and item not in excluded_folders:
            folders.append(item)

    presets = {
        "JS": {
            "name": "JavaScript",
            "config": {
                "bg": "linear-gradient(135deg, #111111 0%, #323330 100%)",
                "header": "#f7df1e", 
                "text_h": "#000000", 
                "card": "rgba(247, 223, 30, 0.1)",
                "content_bg": "#ffffff", 
                "content_text": "#f7df1e", 
                "lang": "javascript",
                "pasta": "JS", 
                "desc": "✨ Interatividade e Front-end moderno"
            }
        },
        "PY": {
            "name": "Python",
            "config": {
                "bg": "linear-gradient(135deg, #021d33 0%, #033a63 100%)",
                "header": "linear-gradient(to right, #3776ab, #ffde57)", 
                "text_h": "#021d33", 
                "card": "rgba(255, 255, 255, 0.05)", 
                "content_bg": "#1e1e26", 
                "content_text": "#ffffff", 
                "lang": "python", 
                "pasta": "PY", 
                "desc": "🐍 Automação e Inteligência de Dados"
            }
        },
        "GAMES": {
            "name": "Games",
            "config": {
                "bg": "linear-gradient(135deg, #0f0524 0%, #3b0a66 100%)",
                "header": "linear-gradient(to right, #00ffcc, #0088ff)", 
                "text_h": "#000000", 
                "card": "rgba(0, 255, 204, 0.1)", 
                "content_bg": "#0a0a0a", 
                "content_text": "#00ffcc", 
                "lang": "python", 
                "pasta": "GAMES", 
                "desc": "🎮 Experiências Imersivas e Jogos"
            }
        },
        "QRcode": {
            "name": "Mobile",
            "config": {
                "bg": "linear-gradient(135deg, #0d0221 0%, #240b36 100%)",
                "header": "#e91e63", 
                "text_h": "#ffffff", 
                "card": "rgba(233, 30, 99, 0.1)", 
                "content_bg": "#ffffff", 
                "content_text": "#ffffff", 
                "lang": "markdown",
                "pasta": "QRcode", 
                "desc": "📱 Soluções Mobile e QR Codes"
            }
        },
        "AP": {
            "name": "Analise",
            "config": {
                "bg": "linear-gradient(135deg, #000428 0%, #004e92 100%)",
                "header": "#ffffff", 
                "text_h": "#000428", 
                "card": "rgba(255, 255, 255, 0.1)", 
                "content_bg": "rgba(255, 255, 255, 0.05)", 
                "content_text": "#ffffff", 
                "lang": "markdown",
                "pasta": "AP", 
                "desc": "📊 Transformando dados em decisões"
            }
        }
    }

    dynamic_themes = {}

    for folder in folders:
        # Match case-insensitive preset
        matched_preset_key = None
        for key in presets:
            if key.upper() == folder.upper():
                matched_preset_key = key
                break

        if matched_preset_key:
            p = presets[matched_preset_key]
            dynamic_themes[p["name"]] = {**p["config"], "pasta": folder}
            continue

        # Look for theme.json or config.json
        folder_path = os.path.join(root_path, folder)
        custom_config = None
        config_files = [".theme.json", "theme.json", "config.json"]
        for cf in config_files:
            cfp = os.path.join(folder_path, cf)
            if os.path.exists(cfp):
                try:
                    with open(cfp, 'r', encoding='utf-8') as f:
                        custom_config = json.load(f)
                    break
                except Exception as e:
                    pass

        display_name = folder.replace('-', ' ').replace('_', ' ').title()
        if custom_config:
            display_name = custom_config.get("nome", custom_config.get("name", display_name))

        palette = get_palette_for_name(folder)

        # Infere default language
        default_lang = "markdown"
        try:
            if os.path.exists(folder_path):
                files = os.listdir(folder_path)
                ext_count = {}
                for f in files:
                    _, ext = os.path.splitext(f)
                    ext = ext.lower().replace(".", "")
                    if ext:
                        ext_count[ext] = ext_count.get(ext, 0) + 1
                
                if ext_count:
                    max_ext = max(ext_count, key=ext_count.get)
                    if max_ext == "py":
                        default_lang = "python"
                    elif max_ext in ["js", "jsx"]:
                        default_lang = "javascript"
                    elif max_ext in ["ts", "tsx"]:
                        default_lang = "typescript"
                    elif max_ext == "html":
                        default_lang = "html"
                    elif max_ext == "css":
                        default_lang = "css"
                    elif max_ext == "json":
                        default_lang = "json"
                    elif max_ext == "sql":
                        default_lang = "sql"
        except Exception:
            pass

        dynamic_themes[display_name] = {
            "bg": custom_config.get("bg", palette["bg"]) if custom_config else palette["bg"],
            "header": custom_config.get("header", palette["header"]) if custom_config else palette["header"],
            "text_h": custom_config.get("text_h", palette["text_h"]) if custom_config else palette["text_h"],
            "card": custom_config.get("card", palette["card"]) if custom_config else palette["card"],
            "content_bg": custom_config.get("content_bg", palette["content_bg"]) if custom_config else palette["content_bg"],
            "content_text": custom_config.get("content_text", palette["content_text"]) if custom_config else palette["content_text"],
            "lang": custom_config.get("lang", default_lang) if custom_config else default_lang,
            "pasta": folder,
            "desc": custom_config.get("desc", custom_config.get("description", palette["desc"])) if custom_config else palette["desc"]
        }

    return dynamic_themes

def list_projects(folder):
    root_path = os.getcwd()
    pasta_alvo = os.path.join(root_path, folder)

    if not os.path.exists(pasta_alvo):
        return []

    output = []
    try:
        items = os.listdir(pasta_alvo)
        for item in items:
            caminho_completo = os.path.join(pasta_alvo, item)
            
            is_hidden_or_config = item.startswith(".") or item.lower() in ["theme.json", "config.json"]
            if os.path.isfile(caminho_completo) and not is_hidden_or_config:
                _, ext = os.path.splitext(item)
                ext = ext.lower().replace(".", "")

                tipo = "texto"
                if ext in ["png", "jpg", "jpeg", "webp", "gif"]:
                    tipo = "imagem"
                elif ext in ["py", "js", "html", "css", "sql", "json", "ts", "tsx"]:
                    tipo = "codigo"

                conteudo = ""
                if tipo != "imagem":
                    try:
                        with open(caminho_completo, 'r', encoding='utf-8', errors='ignore') as f:
                            conteudo = f.read()
                    except Exception:
                        pass

                if tipo == "texto" and conteudo.strip().startswith("http"):
                    tipo = "link"

                output.append({
                    "nome": item,
                    "caminho_relativo": f"{folder}/{item}",
                    "tipo": tipo,
                    "ext": ext,
                    "conteudo": conteudo
                })
        
        output.sort(key=lambda x: x["nome"])
    except Exception as e:
        sys.stderr.write(f"Error: {str(e)}\n")
        
    return output

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Script Python do Hubert para listar projetos.")
    parser.add_argument("--type", choices=["themes", "projects"], required=True, help="Tipo de varredura.")
    parser.add_argument("--folder", help="Pasta a varrer (usada para projects).")
    
    args = parser.parse_args()
    
    if args.type == "themes":
        print(json.dumps(list_themes(), ensure_ascii=False, indent=2))
    elif args.type == "projects":
        if not args.folder:
            print(json.dumps({"error": "Parâmetro --folder é obrigatório."}, ensure_ascii=False))
            sys.exit(1)
        print(json.dumps(list_projects(args.folder), ensure_ascii=False, indent=2))
